services:
  image-trainer:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #        - driver: nvidia
    #          device_ids: [all]
    #          capabilities: [gpu]
    network_mode: host
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    env_file:
      - d.env
    # command:
    #   [
    #     "python",
    #     "/home/user/YOLO/YOLO/download_script.py",
    #     "crlab",
    #     "redi/",
    #   ]
